def earnings_columns():

	cols = ['Date', 'Treasury Shares Number', 'Ordinary Shares Number',
	'Share Issued', 'Net Debt', 'Total Debt', 'Tangible Book Value',
	'Invested Capital', 'Working Capital', 'Net Tangible Assets',
	'Capital Lease Obligations', 'Common Stock Equity',
	'Total Capitalization', 'Total Equity Gross Minority Interest',
	'Minority Interest', 'Stockholders Equity',
	'Gains Losses Not Affecting Retained Earnings',
	'Other Equity Adjustments', 'Treasury Stock', 'Retained Earnings',
	'Additional Paid In Capital', 'Capital Stock', 'Common Stock',
	'Total Liabilities Net Minority Interest',
	'Total Non Current Liabilities Net Minority Interest',
	'Other Non Current Liabilities', 'Employee Benefits',
	'Non Current Pension And Other Postretirement Benefit Plans',
	'Tradeand Other Payables Non Current',
	'Non Current Deferred Liabilities',
	'Non Current Deferred Taxes Liabilities',
	'Long Term Debt And Capital Lease Obligation',
	'Long Term Capital Lease Obligation', 'Long Term Debt',
	'Current Liabilities', 'Other Current Liabilities',
	'Current Deferred Liabilities', 'Current Deferred Revenue',
	'Current Debt And Capital Lease Obligation',
	'Current Capital Lease Obligation', 'Current Debt',
	'Other Current Borrowings', 'Line Of Credit', 'Commercial Paper',
	'Pensionand Other Post Retirement Benefit Plans Current',
	'Payables And Accrued Expenses', 'Current Accrued Expenses', 'Payables',
	'Total Tax Payable', 'Income Tax Payable', 'Accounts Payable',
	'Total Assets', 'Total Non Current Assets', 'Other Non Current Assets',
	'Defined Pension Benefit', 'Non Current Deferred Assets',
	'Non Current Deferred Taxes Assets', 'Non Current Accounts Receivable',
	'Investments And Advances', 'Investmentin Financial Assets',
	'Long Term Equity Investment', 'Goodwill And Other Intangible Assets',
	'Other Intangible Assets', 'Goodwill', 'Net PPE',
	'Accumulated Depreciation', 'Gross PPE', 'Construction In Progress',
	'Other Properties', 'Machinery Furniture Equipment',
	'Buildings And Improvements', 'Land And Improvements', 'Properties',
	'Current Assets', 'Other Current Assets', 'Hedging Assets Current',
	'Restricted Cash', 'Prepaid Assets', 'Inventory', 'Finished Goods',
	'Work In Process', 'Raw Materials', 'Receivables', 'Other Receivables',
	'Accounts Receivable', 'Allowance For Doubtful Accounts Receivable',
	'Gross Accounts Receivable',
	'Cash Cash Equivalents And Short Term Investments',
	'Other Short Term Investments', 'Cash And Cash Equivalents']

	return cols